import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

// Reproducibility invariant (HARDENING-PLAN Phase 6.5 — F-01 detection).
//
// The released `main.js` is only auditable if a third party can rebuild it
// from the tagged source and get the same bytes. That requires the build to
// embed nothing that varies between runs: no build timestamp, no hostname, no
// absolute path, no counter, no `Date` of any kind.
//
// The banner below is a fixed string and is the ONLY thing this config injects
// into the output. It contains no date, so there is nothing here for
// `SOURCE_DATE_EPOCH` to normalise — deliberately, because a build that has no
// clock input is stronger than one that has a clock input pinned by an
// environment variable a release job might forget to set. Verified: two
// consecutive `node esbuild.config.mjs production` runs, and a run from a
// clean `pnpm install --frozen-lockfile` tree in a different directory, all
// produce an identical sha256.
//
// If a future change ever needs a date in the output (a version stamp, a build
// ID), read it from `process.env.SOURCE_DATE_EPOCH` with a fixed fallback —
// never from `Date.now()` — and keep `pnpm check:reproducible` green.
// `scripts/verify-reproducible-build.mjs` is what enforces this; it runs in PR
// CI and fails the build the moment the output stops being byte-stable.
//
// Note that `sourcemap: 'inline'` is dev-only: the production path sets it to
// `false`, so no absolute source path reaches the shipped bundle.
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const oneShot = prod || (process.argv[2] === 'dev');

const prodBanner = prod ? 'console.debug = function() {};\n' : '';

const context = await esbuild.context({
  banner: {
    js: banner + prodBanner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map((module) => `node:${module}`)],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (oneShot) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
